from pydantic import BaseModel, Field
from typing import List, Optional

# --- Shared Card Structure ---
class Card(BaseModel):
    id: str = Field(description="Unique UUID generated by backend")
    type: str = Field(description="'text' | 'link' | 'image' | 'email'")
    title: str = Field(description="Derived card title or Gemini-summarized header")
    summary: str = Field(description="A short 1-2 sentence aesthetic/content summary of the item")
    entities: List[str] = Field(default_factory=list, description="Aesthetic tags, colors, themes, materials, or brands")
    url: Optional[str] = Field(None, description="Source URL or Image URL if applicable")
    cover_image: Optional[str] = Field(None, description="Displayable preview image (data URL for uploads, og:image for links, or direct image URL)")
    visual_features: Optional[str] = Field(None, description="Visual description (colors, texture, shape) if image/visual link")
    
    # Email specific first-class fields
    sender: Optional[str] = Field(None, description="Sender of the email (From field)")
    subject: Optional[str] = Field(None, description="Subject line of the email")
    date: Optional[str] = Field(None, description="Date or timestamp of the email")
    body_summary: Optional[str] = Field(None, description="A concise 1-2 sentence summary of the email body content")
    
    # Spatial positioning
    x: float = Field(0.0, description="X coordinate on canvas")
    y: float = Field(0.0, description="Y coordinate on canvas")

# --- Ingest Agent ---
class IngestRequest(BaseModel):
    content: str = Field(description="Raw text, email text, or URL dropped by the user")
    hint: Optional[str] = Field(None, description="Optional type hint such as 'email' to force specific parsing")

# --- Curate Agent ---
class Cluster(BaseModel):
    id: str = Field(description="Generated cluster ID")
    label: str = Field(description="Creative thematic label, e.g., 'Warm Minimalist Oak'")
    card_ids: List[str] = Field(description="List of card IDs belonging to this cluster")

class CurateRequest(BaseModel):
    cards: List[Card] = Field(description="All cards on the spatial canvas")

class CurateResponse(BaseModel):
    clusters: List[Cluster] = Field(description="Categorized grouping of existing cards")
    taste_profile: str = Field(description="A synthesized creative paragraph describing the user's design style or core interest focus")
    gaps: List[str] = Field(description="3-5 items/styles currently missing that would perfect this vibe")

# --- Orchestrate Agent ---
class ScoutDispatch(BaseModel):
    cluster_id: str = Field(description="Target cluster ID to enrich")
    priority: str = Field(description="'high' | 'medium' | 'low'")
    search_hints: List[str] = Field(description="Highly descriptive search queries to locate missing gaps")

class OrchestrateRequest(BaseModel):
    clusters: List[Cluster]
    taste_profile: str
    gaps: List[str]

class OrchestrateResponse(BaseModel):
    scout_dispatches: List[ScoutDispatch] = Field(description="Tasks dispatched for scouting")

# --- Scout Agent ---
class Candidate(BaseModel):
    title: str = Field(description="Product or image recommendation name")
    url: str = Field(description="Simulated shopping/reference URL matching search hint")
    price: Optional[str] = Field(None, description="Estimated price (e.g. '$120') if applicable")
    image_url: Optional[str] = Field(None, description="Placeholder or simulated visual match")
    emoji: Optional[str] = Field(None, description="Single emoji representing the candidate, used as a visual fallback when no image is available")
    match_reason: str = Field(description="Explanation of why this candidate fits the user's taste and gaps")

class ScoutRequest(BaseModel):
    cluster_id: str
    cluster_label: str
    search_hints: List[str]
    taste_profile: str
    user_currency: Optional[str] = Field("USD", description="3-letter ISO currency code for displaying prices")
    cluster_cards: Optional[List[dict]] = Field(
        default_factory=list,
        description="Cards belonging to this cluster (title, summary, entities, visual_features, type) for the scout to reason about.",
    )


# --- Feedback ---
class FeedbackRequest(BaseModel):
    reason: Optional[str] = Field(None, description="User's explanation; may be empty.")
    suggestion_title: Optional[str] = Field(None, description="Title of the dismissed candidate for context.")
    suggestion_url: Optional[str] = Field(None, description="URL of the dismissed candidate for context.")
    cluster_id: Optional[str] = Field(None, description="Cluster the suggestion belonged to, if known.")


class FeedbackResponse(BaseModel):
    ok: bool
    timestamp: str

class ScoutResponse(BaseModel):
    candidates: List[Candidate] = Field(description="List of scouted suggestions")

# --- Stage Agent ---
class StageRequest(BaseModel):
    url: str = Field(description="URL to stage in the browser")

class StageResponse(BaseModel):
    status: str = Field(description="'success' | 'failed'")
    screenshot_path: Optional[str] = Field(None, description="Path to screenshot of the staged cart page")


# --- Extension browser bridge ---
class BrowserResultRequest(BaseModel):
    action_id: str
    result: Optional[dict] = None
    error: Optional[str] = None


class ExtensionHelloRequest(BaseModel):
    version: Optional[str] = None
